### ISSUE TITLE
mime-types extension does not work with default headers

### ISSUE THREAD

**Issue by halostatue** [rest-client/rest-client#284]
The details are covered deeply in lemurheavy/coveralls-ruby#49—it appears that there's a small cascading series of errors that I'm not quite figuring out.

I've also got a comment in #248, but I'm thinking that these items aren't necessarily related.

This is an _unusual_ situation, to be sure—as I'm working on `mime-types` for a new release, which means that the version of mime-types is 2.x. Aside from the incompatibility with Ruby 1.8, there's no other known API incompatibility (2.3 will be fixing a bug that broke that compatibility; that's currently in `master`)—so this should Just Work.

As noted there:

> This _appears_ to be a bug in `rest-client` related to stringifying headers where it's expecting that the default `Accept` header is `*/*; q=0.5, application/xml` and it won't work with the extension that they added to MIME::Types (`type_for_extension`). I'm honestly not sure how it's supposed to have worked with the default header that's present…

This only works if `accept` is something like: `:accept => :json`, not if it's already a MIME content type (e.g., `:accept => 'application/json'`).

**Comment by ab** [comment]
OK after spending some time staring at it, I think I understand what the code is trying to do. It's looking for a direct way to look up a mime type by the extension without any other parsing. (i.e. If there were some way to call `MIME::Types.type_for` and treat it as the whole input rather than splitting off after a `.`)

For now I'm going to rewrite this to be a little bit more defensive and just use `MIME::Types.type_for`, but it might be nice to have a method that would directly look up mime types in the `@extension_index`. (I'd be happy to prepare a PR for that if you have interest.)

**Comment by halostatue** [comment]
@ab :+1: to a PR. It may be a short time before I can do this.

If you need this to work on mime-types 1.x, we will need two PRs against the appropriate branches/tags, but I would much prefer only a 2.x patch.
