### ISSUE TITLE
Requirements needs update after 1.8.0

### ISSUE THREAD

**Issue by superseb** [rest-client/rest-client#371]
Release 1.8.0 adds a dependency to http-cookie gem, which resolves in dependencies to domain_name, unf and unf_ext which needs a C++ compiler and libstdc++ (https://github.com/knu/ruby-unf_ext, Requirement)

This breaks on systems not installing build-tools by default. See this post by example http://stackoverflow.com/questions/29290775/chef-build-error-on-aws-linux-ami

Related logging:

gem executables will not run. ERROR:  Error installing rest-client:
        ERROR: Failed to build gem native extension.
extconf.rb checking for main() in -lstdc++... **\* extconf.rb failed
**\* Could not create Makefile due to some reason, probably lack of necessary libraries and/or headers.  Check the mkmf.log file for more details.  You may need configuration options.

/opt/chefdk/embedded/lib/ruby/2.1.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError) You have to install development tools first.
        from /opt/chefdk/embedded/lib/ruby/2.1.0/mkmf.rb:552:in`try_link0'
        from /opt/chefdk/embedded/lib/ruby/2.1.0/mkmf.rb:567:in `try_link'
        from /opt/chefdk/embedded/lib/ruby/2.1.0/mkmf.rb:753:in`try_func'
        from /opt/chefdk/embedded/lib/ruby/2.1.0/mkmf.rb:984:in `block in have_library'
        from /opt/chefdk/embedded/lib/ruby/2.1.0/mkmf.rb:929:in`block in checking_for'
        from /opt/chefdk/embedded/lib/ruby/2.1.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from /opt/chefdk/embedded/lib/ruby/2.1.0/mkmf.rb:321:in`open'
        from /opt/chefdk/embedded/lib/ruby/2.1.0/mkmf.rb:351:in `block in postpone'
        from /opt/chefdk/embedded/lib/ruby/2.1.0/mkmf.rb:321:in`open'
        from /opt/chefdk/embedded/lib/ruby/2.1.0/mkmf.rb:347:in `postpone'
        from /opt/chefdk/embedded/lib/ruby/2.1.0/mkmf.rb:928:in`checking_for'
        from /opt/chefdk/embedded/lib/ruby/2.1.0/mkmf.rb:979:in `have_library'
        from extconf.rb:2:in`<main>'

extconf failed, exit code 1

Gem files will remain installed in /.chefdk/gem/ruby/2.1.0/gems/unf_ext-0.0.6 for inspection. Results logged to /.chefdk/gem/ruby/2.1.0/extensions/x86_64-linux/2.1.0/unf_ext-0.0.6/gem_make.out
---- End output of /opt/chefdk/embedded/bin/gem install rest-client -q --no-rdoc --no-ri -v "1.8.0" ---- Ran /opt/chefdk/embedded/bin/gem install rest-client -q --no-rdoc --no-ri -v "1.8.0" returned 1

**Comment by dblessing** [comment]
This is a major bummer. I don't want dev tools on all my systems.

**Comment by dblessing** [comment]
Can anyone comment on this issue and at least let us know what you're thinking? Lots of projects are running into this issue and the best solution at the moment is to pin rest-client dependency to < 1.8.0. That seems like something rest-client project would want to address before more projects permanently depend on older versions. @ab I'm going to tag you since you seem to be the most active committer at the moment. Thanks for taking a look.

**Comment by ab** [comment]
Hmm, that's unfortunate.

The `http-cookie` dependency was added due to https://github.com/rest-client/rest-client/issues/369 / CVE-2015-1820. In short, rest-client's handling of cookies in versions < 1.8.0 was based on a regex that didn't remotely implement what the RFCs for HTTP cookies specify.

There were a couple different potential options:

1. Remove the cookie functionality entirely (not very appealing)
2. Attempt to reimplement the functionality of `http-cookie` and `domain_name` myself
3. Add the dependency on `http-cookie`, knowing the added dependencies might be problematic to some users
4. Try to find some other fully-featured cookie implementation for ruby that does not require any C extensions

They all have downsides, but option 3 seemed far and away the least bad. The `domain_name` code uses `unf` here: https://github.com/knu/ruby-domain_name/blob/212b08e4/lib/domain_name.rb#L289 in handling of punycode domain names. I'm not sure why a C extension is needed, so it would probably be best to follow up there.

**Comment by jblaine** [comment]
Purely to throw our situation's info in the pile, I'll second @dblessing re: "major bummer". We've had rest-client pinned to 1.7.3 for 8 months now due to us not only "not wanting dev tools installed on all hosts", but literally not being allowed to have them installed due to compliance/auditing requirements.

That said, this is Open Source. We do appreciate that rest-client exists.

**Comment by ab** [comment]
Just updating status here, you can avoid the need for `unf_ext` on Ruby >= 2.2 by installing `unf` version `0.2.0beta1`. For example, by `gem install --pre unf`.

Still hoping that this will make it into a final release version of `unf`.
