### ISSUE TITLE
Buffered output to fd

### ISSUE THREAD

**Issue by ioquatix** [rest-client/rest-client#379]
Is it possible to write data directly to a file?

e.g.

`RestClient.get("...", :out => File.open(path, "w"))`

**Comment by ab** [comment]
The API doesn't support quite what you want directly, but you should be able to get something similar with `:raw_response` or `:block_response`.

`:raw_response` will save the raw response to a file. Note that this really is the *raw* response. It may be gzipped or otherwise encoded.
```
res = RestClient::Request.execute(method: :get, url: 'http://example.com', raw_response: true)
File.read(res.file.path)
```

Or  you can use the `:block_response` argument, which takes a block that will be passed the raw Net::HTTP response object. You can call `read_body` on it:
```
File.open(path, 'w') do |out|
  RestClient::Request.execute(method: :get, url: 'http://example.com', block_response: proc {|res|
    res.read_body {|chunk| out.write(chunk) }
  })
end
```

**Comment by ioquatix** [comment]
@ab this is awesome, perhaps this could be part of the README.md?

**Comment by ab** [comment]
Yeah the docs are in sore need of attention. I've been focusing on getting 2.0 out instead. Patches are most welcome. :-)

**Comment by ioquatix** [comment]
Can I rewrite the README.rdoc to README.md ?
