### ISSUE TITLE
Cannot test for instance_of? RestClient::Response

### ISSUE THREAD

**Issue by darrenleeweber** [rest-client/rest-client#384]
A RestClient::Response appears to be a String class, although it can respond to non-stringy methods like #headers and #code.  There is no easy way to validate that an object is a RestClient::Response instance, other than to check whether it can respond_to? :headers or :code.  (It's OK if this is a "won't fix" issue, but it would be great to have an explanation and possibly advice on the recommended way to detect a RestClient::Response instance.)

**Comment by ab** [comment]
Yep, that's a long standing (really bad) known bug. It won't be fixed until 3.0 since it's very dramatically not backwards compatible.

In code, you can tell the difference with `obj.is_a?(RestClient::Response)`.

You'll be pleased to find that RestClient on master at least defines a sensible `Response#inspect` method so that you can visually tell the difference as well. The next version of RestClient will also return a true `String` object when you call `Response#body` so that there is a better way to get a plain string object than calling `String.new(resp)`.
