### ISSUE TITLE
Is the response object a string or something else?

### ISSUE THREAD

**Issue by iMerica** [rest-client/rest-client#408]
Hey guys,

I noticed this peculiar behavior

```ruby
response = RestClient.get('http://jsonip.com/')
response.class
# => String

response.code
# => 200

"This is a string".code
# => NoMethodError: undefined method `code' for "This is a string":String

response == response.body
# => true
```
Did you guys monkey patch the String class to provide this behavior or am I missing something?

The reason I'm asking is that I'm building a wrapper on top of rest-client and all operations are going to respond with a hash e.g `JSON.parse(RestClient.get(url))`.  How can I get the entire response object fields into the JSON itself? So that I don't have to do:

```ruby
def get_response_as_json(url)
  response = RestClient.get(url)
  json = JSON.parse(response)
  json['code'] = response.code
  json
end
```

Kind regards,

Michael

**Comment by ab** [comment]
The bad news:

This behavior has been around since the earliest days of rest-client and is super confusing and awful. Response objects are normal String objects that have extra Response related functionality mixed in at run time. So `response.class` is `String`, the original `String` class is unchanged, yet the `response` instance has a bunch of functionality that comes from `RestClient::AbstractResponse`.

The good news:

This is all changing for rest-client 2.0 in a mostly backwards-compatible way. Response objects will continue to quack like Strings, but now by virtue of being a subclass of String rather than the previous Frankenstein hybrid. 

Better still, the new Response objects will override `.inspect` so it's not so dang confusing:

```
>> RestClient.get('http://example.com')
=> <RestClient::Response 200 "<!doctype h...">
```

As for putting the whole thing into a hash:

Broadly speaking, an HTTP response consists of a response code, some headers, and a body. You probably do want a wrapper, and you probably want to JSON.parse the `response.body`. In rest-client 2.0, the `#body` and `#to_s` methods will return a true String object rather than the current crazy hybrid. You can also store the `response.code` and `response.headers` or `response.raw_headers` somehow if you like.

**Comment by iMerica** [comment]
Good to know - thanks @ab! Looking forward to v2.0!
