### ISSUE TITLE
Cookies JAR clarification

### ISSUE THREAD

**Issue by daluu** [rest-client/rest-client#471]
From the README:

> New in 1.8: An HTTP::CookieJar of cookies

> Response objects now carry a cookie_jar method that exposes an HTTP::CookieJar of cookies, which supports full standards compliant behavior.

I'm not really familiar with Ruby's HTTP:CookieJar, but can it be used with requests? As in construct the cookie JAR then pass into request instead of using a cookie hash or string. Or is it currently only for responses? If the latter, any plans to support a cookie JAR in requests in the future?

**Comment by ab** [comment]
The `cookie_jar` was introduced into Response objects because the existing rest-client code was so broken in its handling of cookies that it created security vulnerabilities. Right now there's no way to pass in an `HTTP::CookieJar` when initializing a request, but I'm planning to add that functionality for the `2.0.0` release.

https://github.com/sparklemotion/http-cookie
