### ISSUE TITLE
Passing a curl argumet to rest-client -T

### ISSUE THREAD

**Issue by demonmind** [rest-client/rest-client#514]
I have an api call and the only example the have is a curl example for a file upload like so:

```
curl -X PUT "**assetUrl**" -H "**authorization**" -H "x-amz-acl:**amzAcl**" -H "**contentType**" -H "x-amz-date: **amzDate**" -T **path/to/local/file**
```

How can i pass that -T option to rest-client?

**Comment by ab** [comment]
Have you looked at the docs around multipart?

https://github.com/rest-client/rest-client/blob/adb990b/README.md#multipart

Or, since by that example it looks like you're intending to do an S3 upload, perhaps you wanted the file to be the entire HTTP PUT body?

For that case you can just use `File.open('path/to/local/file')` as the body/payload.
