### ISSUE TITLE
RestClient reads my ftp credentials in ~/.netrc to do unexpected basic_auth

### ISSUE THREAD

**Issue by Arczzir** [rest-client/rest-client#524]
v2.0.0 request.rb:816

``` ruby
    def setup_credentials(req)
      req.basic_auth(user, password) if user && !headers.has_key?("Authorization")
    end
```

1) RestClient shouldn't read netrc credentials as `user` unexpectedly 
2) Specifying :authorization key in header should also be able to skip this stealth as well as "Authorization"

The current behavior makes endless 401s :(

**Comment by ab** [comment]
Yeah that seems like not great behavior.

**Comment by timmc** [comment]
It also turns out that if the .netrc is incomplete (e.g. `machine foo login bar password` but no actual password) then netrc and therefore restclient error out. This is how I finally discovered why our apitests had stopped working on my machine -- I had had a well-formed .netrc, which caused test failures, and only when I removed the password did the tests break in a way that led me to this ticket.
