### ISSUE TITLE
File Encoding Issues while Streaming

### ISSUE THREAD

**Issue by willisjtc** [rest-client/rest-client#534]
I am using RestClient to stream some files from websites and am running into encoding issues when I write to disk. I'm following this example:

```
File.open('/tmp/foo.iso', 'w') {|f|
    block = proc { |response|
      response.read_body do |chunk|
        puts "Working on response" 
        f.write chunk
      end
    }
    RestClient::Request.new(method: :get, url: 'http://mirror.pnl.gov/releases/xenial/ubuntu-16.04-server-amd64.iso', block_response: block).execute
}
```

found as a solution in this issue: https://github.com/rest-client/rest-client/issues/452.

I'm getting an assortment of byte encoding errors: Unable to retrieve file.ext - `"\\xB5\" from ASCII-8BIT to UTF-8`, `"\\x8B\" from ASCII-8BIT to UTF-8`, `"\\xBF\" from ASCII-8BIT to UTF-8`. The chunk looks like this coming into the proc:

```
]???0??>?-?A
            ?11L?
                 ??Z?ؤRB?Oo????ݗ?Q?na;??ūAj?Pl??H??a
                                                    q????Q??T?N?Z?$?7gͤhD?b?9???.A?䱴.ȑE "?)ge??;-:??=??j?47m??9??Tz@???6t?^Х??`D?{cǯo8?\????R????
```

I tried running something like this: `force_encoding("ASCII-8BIT").encode('UTF-8', undef: :replace, replace: '')` but that didn't end up working either.

What's interesting is that if retrieve the file into memory, RestClient handles all the encoding automatically and I don't get these errors.

What can I do to get these encodings errors situated and stream these files properly?

**Comment by ab** [comment]
Hmm I don't totally understand what's happening here. I'm also not able to reproduce the issue using your script. RestClient shouldn't be doing anything special with the encoding no matter whether you use a block because there's no `charset` in the `Content-Type` header sent by pnl.gov.

What platform/version are you running on? e.g. `ruby -r rest-client -e 'puts RestClient::Platform.default_user_agent'`

Since this is binary data, you don't want ruby to be treating it as UTF-8 at any time. What is `chunk.encoding` in the block there? If it's not already `Encoding:ASCII-8BIT`, something has gone wrong. You might try doing `force_encoding('ASCII-8BIT')` and nothing else. 

If you're on windows, have you tried opening the output file with mode `wb` to instruct it to use binary mode?

**Comment by ab** [comment]
Feel free to reopen with more info.

**Comment by hacxman** [comment]
Howdy ho!
I've managed to figure out what is going on at least on a surface.
Look:
$ irb
2.4.1 :001 > ENV['LANG']
 => "en_US.utf8" 
2.4.1 :002 > "asdfasdf".encoding
 => #<Encoding:UTF-8> 
2.4.1 :003 > 


$ LANG="C" irb
2.4.1 :001 > ENV['LANG']
 => "C" 
2.4.1 :002 > "asdfasdf".encoding
 => #<Encoding:US-ASCII> 
2.4.1 :003 > 


When I did force_encoding('UTF-8') on chunk passed into blocks body, it started to work.
