### ISSUE TITLE
Dependency on old version of netrc gem

### ISSUE THREAD

**Issue by dominicsayers** [rest-client/rest-client#546]
This project depends on a 2-year-old version of the `netrc` gem. 

`s.add_dependency('netrc', '~> 0.8')`

There are other gems I would like to use that depend on newer versions. Is there a reason why the version needs to be so restricted?

**Comment by ab** [comment]
`~>` is a pessimistic version constraint, so that dependency reads as `'>= 0.8', '< 1.0'`. The current latest version of netrc is `0.11.0`, so there shouldn't be any issue with using that version.

Perhaps you wanted to remove your Gemfile.lock or run `bundle update`?

http://guides.rubygems.org/patterns/#pessimistic-version-constraint
