### ISSUE TITLE
Streamed payload not working

### ISSUE THREAD

**Issue by HeyuimSara** [rest-client/rest-client#553]
I have a large file, and I need to upload it's content to server. Rather than reading it all into memory, I want to upload it as a stream, but RestClient::Payload::Streamed seems not working as I expected.

My ruby version:
ruby 2.0.0p195 (2013-05-14 revision 40734) [x86_64-linux]

My code:
```
      read_file = File.new("filepath_here", "r+b")

      payload = RestClient::Payload.generate(read_file)

      request = RestClient::Request.new(method: :post, url: 'upload endpoint', payload: payload)

      request.execute

```

When I ran the code, I can read from log:
```
2016-11-28T07:25:41.953492+00:00 [ERROR]    delayed_job.0.13883 , upload.rb:128                      , undefined method `closed?' for "":RestClient::Payload::Streamed /home/cpsuser/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/rest-client-1.6.7/lib/restclient/payload.rb:109:in `close'
2016-11-28T07:25:41.953492+00:00 [ERROR]    delayed_job.0.13883 , upload.rb:128                      , /home/cpsuser/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/rest-client-1.6.7/lib/restclient/request.rb:66:in `execute'
```

I can get docs on how to use RestClient::Payload::Streamed nowhere, if the usage is wrong, would you please document it somewhere? Please help, thanks.

**Comment by ab** [comment]
Ugh, yes, the API here is ugly and the docs are poor.

Very belatedly, in case someone still runs into this:

You probably shouldn't call `Payload.generate` yourself, because whatever is passed as the `payload: foo` will get sent to `Payload.generate` again, and `Payload.generate` is not smart enough to realize that it already has a Payload on its hands. (In my opinion, this is a wart, and should be fixed in a future version of rest-client.)

Here are some examples for how to do it:

### Streaming payload body

```ruby
# Use a large file directly as the payload content
RestClient::Request.execute(method: :post, url: 'upload endpoint', payload: File.new('huge_file', 'r'))
```

### Multipart file upload

For a multipart file upload — `Content-Type: multipart/form-data`, pass a File in a Hash. Note that `Payload::Multipart` does do streaming uploads, but first it copies all the files into a Tempfile, which is probably not desirable for large files.

```ruby
# Multipart upload via tmpfile
RestClient::Request.execute(method: :post, url: 'upload endpoint', payload: {my_file_field: File.new('huge_file', 'r')})
```
