### ISSUE TITLE
Timeout not working

### ISSUE THREAD

**Issue by andricicezar** [rest-client/rest-client#561]
If the server is reacheable, the timeout works, but if the server is unreacheable, the timeout doesn't work and the request is not canceled after 2 seconds.

There is any workaround for that?

```
       res = RestClient::Request.execute(
         method: :post,
         url: service_link,
         payload: { query: query(args) },
         timeout: 2)
```

**Comment by ab** [comment]
What version of rest-client are you running? I'm not able to reproduce this.

```
>> RestClient::Request.execute(method: :get, url: 'http://example.com:1231', timeout: 2)
RestClient::Exceptions::OpenTimeout: Timed out connecting to server
```

**Comment by andricicezar** [comment]
From `Gemfile.lock`: `rest-client (>= 1.6.7)`

**Comment by andricicezar** [comment]
I don't know if this is a valid test, but why it takes so long?
```
[12] pry(main)> puts Time.now; begin; RestClient::Request.execute(method: :get, url: 'http://example.com:1231', timeout: 1); rescue; puts Time.now; end
2017-01-06 19:58:01 +0000
2017-01-06 19:58:05 +0000
```

The weird part, and my use case, is that I need to access a Docker Container and I have something like `http://microservice`. Seems like there are needed ~8 seconds to complete this kind of request:
```
[13] pry(main)> puts Time.now; begin; RestClient::Request.execute(method: :get, url: 'http://FIRST_API', timeout: 1); rescue; puts Time.now; end
2017-01-06 19:58:48 +0000
2017-01-06 19:58:56 +0000
```

**Comment by ab** [comment]
I'd wager there's a problem somewhere in your networking stack (e.g. DNS?) that is taking some time.

Running that same test showing the times I see:

```
>> puts Time.now.utc; begin; RestClient::Request.execute(method: :get, url: 'http://example.com:1231', timeout: 1); rescue => err; puts err.inspect; end; puts Time.now.utc
2017-01-07 20:29:07 UTC
#<RestClient::Exceptions::OpenTimeout: Timed out connecting to server>
2017-01-07 20:29:08 UTC
```

But it's also worth noting that the timeout might not be doing what you want it to be doing here. Under the hood rest-client is setting Net::HTTP's `open_timeout` and `read_timeout`. So it does not provide any end-to-end timeout on how long the method call will take.

[open_timeout](https://docs.ruby-lang.org/en/2.0.0/Net/HTTP.html#attribute-i-open_timeout) specifies a timeout on the duration to wait for the initial connection to be established.

[read_timeout](https://docs.ruby-lang.org/en/2.0.0/Net/HTTP.html#attribute-i-read_timeout) specifies a timeout on waiting for each piece of data to come back from the server. It's more like an idle timer, since it resets every time data is received.

So a server that establishes a connection and feeds data in dribs and drabs for a long time won't cause either of these timeouts. If you need an end-to-end timeout on how long the request takes, you could wrap the whole call in Timeout::timeout. But note that [Timeout::timeout can be unsafe](https://jvns.ca/blog/2015/11/27/why-rubys-timeout-is-dangerous-and-thread-dot-raise-is-terrifying/).

Feedback is welcome on how to better document this behavior!

**Comment by ab** [comment]
Feel free to reopen with more info suggesting this is a bug.
