### ISSUE TITLE
Files being dumped to /tmp - Looking for ways to redirect

### ISSUE THREAD

**Issue by nag-cheedella** [rest-client/rest-client#566]
I'm using rest-client with below ruby version

```ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]```

Using the client to do POST call with facebook graph api to upload video files. Sometimes get some files going to /tmp directory and it keeps filling up the space.

```root@facebook-syndication2.us-east-1:/tmp# ls -l RES*
-rw------- 1 root  root  214294528 Jan 22 18:10 RESTClient.Stream.38820170122-11600-dxcr11-0
-rw------- 1 root  root  909291520 Jan 22 18:10 RESTClient.Stream.29720170122-1619-1no52tl-0
```

Here's the REST call that's being made
```
      body = begin
      # e.g CURL call for ref: response = 'curl -F "access_token='+ access_token + '" -F "source=@'+ new_file.path + '" -F "title='+ title +'" -F "description='+ description +'" '+ upload_url
      RestClient.post upload_url, :access_token => access_token, :multipart => true,
        :title => title, :description => description, :source => File.new(new_file.path, 'rb')
    rescue => e
      e.response.body
    end
    response = JSON.parse(body)
```
Questions:

1. I'm not able to capture anything in rescue error trace...  What's the best way to capture the error with this rest-client. I've tried standard error capturing
2. What are these RESTClient* files getting dumped /tmp and is there a way I can re-direct them to a bigger drive on the box so I'll not fill up by /tmp (or my /root).

Thanks

**Comment by ab** [comment]
Very belatedly, those files are created by rest-client while it's formatting multipart files for upload. It uses ruby's native `Tempfile` class to ensure they are cleaned up. It's very odd that they would stick around.

`Tempfile` calls `Dir.tmpdir` to determine where to put the files, so you could redefine it in order to control where those files are placed.

The fact that they are sitting around taking up space suggests that either your program is still running and somehow the Tempfile handle is still held somewhere, or ruby is crashing so badly that it doesn't even run the `ensure` block that removes the tempfiles. Either way not a good situation.

I would not use a bare `rescue => e`, as that will catch a great variety of exceptions. Maybe use something like `rescue RestClient::ExceptionWithResponse => e` instead?

Also, ruby 1.8.7 is extremely old, unsupported since 2013.

**Comment by nag-cheedella** [comment]
Many Thanks for your reply. I'm going to try this solution (redefine Dir.tmpdir) to a different drive that has more space.  Yes, ruby upgrade is also on the to-do list for me.
