### ISSUE TITLE
Using timeout option does not timeout for short period of time

### ISSUE THREAD

**Issue by jonathann92** [rest-client/rest-client#624]
I tried using timeout for 2 seconds and the timeout period was longer than 2 seconds

**Comment by ECasielles** [comment]
We are having the same issue. If the server is unreachable, no timeout exception is thrown.

**Comment by ab** [comment]
RestClient relies upon the Ruby built-in Net:HTTP open_timeout and read_timeout functions. These indeed do not enforce any limit on the total request time. For that, you'll need to implement your own wrapping timeout.

Pull requests are also welcome, but due to the dangers of Timeout::timeout() being not super safe, it's unclear what rest-client could do about this.

https://felipeelias.github.io/ruby/2017/08/20/net-http-timeouts.html
https://medium.com/@adamhooper/in-ruby-dont-use-timeout-77d9d4e5a001
