### ISSUE TITLE
calling inspect on Exception

### ISSUE THREAD

**Issue by aroos** [rest-client/rest-client#631]
Is there a reason why inspect doesn't print the response object, error code, ...?

**Comment by ab** [comment]
Typically exceptions tend to be pretty minimal in terms of their inspect methods, but maybe if you describe what you'd like to see we could consider changes.

**Comment by toxaq** [comment]
As an example: We push all of our exceptions into bug tracking software which tries to open them up as standard exceptions. Because "message" has been overridden to return the class name our tracking is basically junk. We know what the class of exception was caught and that's it. 

So now our options are to write custom code to turn a RestClient exception into something readible by our bug tracking software or standardise RestClient so it returns something consumable.

Thoughts? The most important thing for me when tracking a RestClient is the response body but that is unavailable without custom code.
