### ISSUE TITLE
2.1.0 final?

### ISSUE THREAD

**Issue by michaelsauter** [rest-client/rest-client#643]
2.1.0rc1 was released on July 5th, over 4 months ago. Are there any concerns or known issues that prevent promoting this to 2.1.0 final? Just wondering as we want to update our version of rest-client (< 2.0) and I'm not sure which version to upgrade to for production usage.

**Comment by cben** [comment]
@ab Anything we can do to help towards releasing 2.1?  Issues to debug, code to review, tests to write?

MIchael, even if 2.1 was already out, since 1.x->2.0 had some API changes I'd consider upgrading to 2.0 in a separate step. YMMV.

**Comment by michaelsauter** [comment]
@cben Well, the changelog notes the following for 2.1.0rc1: "Add a dependency on http-accept for parsing Content-Type charset headers. This works around a bad memory leak introduced in Ruby 2.4.x". We are on Ruby 2.4, so I don't want to update to rest-client 2.0.

**Comment by cben** [comment]
Oh, right.
I think that refers to #611.  Note that C leak was fixed in ruby 2.4.2, so if you run an older 2.4 you'll also want to upgrade ruby (rest-client was not the only code to suffer from the leak).

**Comment by michaelsauter** [comment]
@cben Nice, thanks for the hint!

**Comment by magneland** [comment]
Any update on this? We don't specifically need 2.1.0, but we are wondering if rest-client is still being actively maintained?

**Comment by kbrock** [comment]
On our project we're monkey patching `rest-client` to get some of the goodness from the 2.1.0 release.

Is there a timeline for releasing 2.1.0?
Or are there any tasks some developers can take on? (Or assign to @cben  ;) )

**Comment by joshRpowell** [comment]
@kbrock we're also monkey patching here.  just opened #686 and followed up on #657 to see if we can help get the ball rolling.

**Comment by soundasleep** [comment]
Bumping this: I was debugging a bizarre crash on Windows 10 related to rest-client, and it seems upgrading to rest-client github master (i.e. 2.1.x) resolved it.

(`RestClient.get()` would succeed, but the Rails or Sidekiq server would immediately crash afterwards, with zero output: it would go back to the command line. Perhaps it was because on Windows 10, `rest-client (2.0.2-x64-mingw32)` would get installed with `bundle`...)

**Comment by z64** [comment]
+1 @soundasleep - at https://github.com/meew0/discordrb, all of our Windows users (specifically with Ruby 2.5) experienced the exact same issue. Downgrading Ruby or using the release client tag / master as you suggested fixes the issue. We've had to write a native extension to upgrade the dependency when our gem is installed on Windows, so that Linux can stay at `~> 2.0`.

> Perhaps it was because on Windows 10, rest-client (2.0.2-x64-mingw32) would get installed with bundle

2.0.2 is expected to be installed because its the latest stable tag. bundler/gem will not install release client, beta, etc, tags unless you explicitly tell it to do so

**Comment by ab** [comment]
2.1.0 was released yesterday, at long last! As you have seen, maintenance has been dormant for a while now.

If folks like @cben are still interested in taking on ownership, please let me know. Especially in light of  #713, I think it makes sense to codify some more formal expectations around maintainership.

**Comment by cben** [comment]
Sorry, I've shifted projects at work and no longer have significant time for ruby, definitely not up for becoming a maintainer.  I could do small reviews etc.

Until you find more maintainers, is there a type of small contributions that would help *you* move things forward?  E.g. if someone you don't know reviews a PR and pings you "ab, this is low-risk and code makes sense", does that help you merge it faster?  Let the community know what works for you.
