### ISSUE TITLE
Is TLS 1.2 supported?

### ISSUE THREAD

**Issue by boonware** [rest-client/rest-client#653]
The documentation does not explicitly say whether or not TLS 1.2 is supported. It is important to verify this as many services withdraw support for older versions. For example [IBM Cloud is withdrawing support](https://console.bluemix.net/docs/troubleshoot/appsectls.html#tlssupportwithdraw) for anything less than TLS 1.2 from the 1st March 2018.

**Comment by boonware** [comment]
@ab Could you help on this? You seem to be the only active collaborator on this repository.

**Comment by ab** [comment]
Yes, rest-client should support any TLS version that the Ruby OpenSSL
library supports. This will include TLS 1.2 on basically any recent system.
You can configure it with the ssl_version option.

On Feb 7, 2018 5:08 AM, "Joe Harte" <notifications@github.com> wrote:

@ab <https://github.com/ab> Could you help on this? You seem to be the only
active collaborator on this repository.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rest-client/rest-client/issues/653#issuecomment-363719617>,
or mute the thread
