### ISSUE TITLE
Upgrade guide

### ISSUE THREAD

**Issue by madroneropaulo** [rest-client/rest-client#682]
We're updating from Rails 4 to 5, and having a really hard time upgrading from rest-client 1.8 to 2^ 

The way arrays are sent is totally different.
The default headers
The way multipart is handled

What used to be default now seems that has to be written manually, and I feel really lost since we didn't care at all at all these things, I can spend hours to find out that a header is not being sent as before, and we have an extensive codebase with many calls to a third party api. First we tried just leaving the 1.8 but we're getting a "Key not found :ciphers" error (I think due to the newer ruby version). So we must update, and I wonder if there is a complete guide to upgrade from 1.8 to 2^. Thank you!

**Comment by andrykonchin** [comment]
Isn't very helpful but still...
https://github.com/rest-client/rest-client#upgrading-to-rest-client-20-from-1x

**Comment by ab** [comment]
The `KeyError: key not found: :ciphers` issue was fixed in rest-client 2.0.1. https://github.com/rest-client/rest-client/issues/569

I'm sorry you're having difficulty upgrading. In general, all the changes made from rest-client 1.x to 2.x made behavior more consistent and more rigorously defined. Some of the original behavior was very ad-hoc.

You may find it useful to crank up RestClient.log to see what is happening, or better yet to write some of the previously magic behavior like parameter serialization more explicitly. There is no standard for how to serialize complex HTTP parameter data like arrays, so rest-client just has to pick a way to implement it and be consistent about it. If you're unhappy with the result, then it may be easier to implement parameter serialization yourself or use RestClient::ParamsArray for creater control.
