### ISSUE TITLE
Display the Body on exception_with_response

### ISSUE THREAD

**Issue by pescetto** [rest-client/rest-client#683]
Sometimes REST servers respond with error messages in the body, but the `RestClient::AbstractResponse` method `exception_with_response` only returns the code and not the body. 

I'd like to request the feature to return the body if it's not empty somewhere in here:
https://github.com/rest-client/rest-client/blob/master/lib/restclient/abstract_response.rb#L242-L250

That way I don't have to PRY into your gem just to return the body to see why my request failed.

**Comment by raakeshbr1803** [comment]
@pescetto 
`exception_with_response` raises the exception with the response code and its message. If you want to get the response/error_messages try this:

 `begin
     RestClient.get 'http://example.com/nonexistent'
   rescue RestClient::ExceptionWithResponse => e
     e.response.body
   end`

**Comment by ab** [comment]
As already noted, the ExceptionWithResponse objects contain a `#response` method that allows you to get the entire response object along with its body and any other fields.

**Comment by toxaq** [comment]
We use bug tracking software that reports the class name and message (as well as the stacktrace). By duplicating the class name in the message and adding bespoke properties means that this error handling technique needs custom code outside of the standard exception paradigm.

Is there a reason that the error response can't be the message in the exception when the message is blank? Seems like an easy win without a good reason otherwise.

Currently we have:

    rescue RestClient::Exception => re
        ExceptionHelper.track_exception(re)

But what we needed to do to get anything useful is:

    rescue RestClient::Exception => re  
        re.message = re.http_body if re.http_body
        ExceptionHelper.track_exception(re)

And repeat everywhere we catch a RestClient::Exception

This could be done easily within `exceptions.rb` by changing

    def message
      @message || default_message
    end

to 

    def message
      @message || response.body || default_message
    end

or similar (might be better in default_message as a more verbose fallback).

**Comment by Galaxy83** [comment]
monkeypatching:

```
module RestClient
  class Exception
    def message
      return "#{http_code} - #{http_body}" if http_body

      super
    end
  end
end
```
