### ISSUE TITLE
Does not follow redirections automatically for POST requests

### ISSUE THREAD

**Issue by woniesong92** [rest-client/rest-client#695]
When your POST requests gets 302, the client throws.
I tried to catch it and redirect manually but that also failed with the following error:

```
err.response.follow_redirection
*** RestClient::MethodNotAllowed Exception: 405 Method Not Allowed
```

**Comment by ab** [comment]
The semantics of HTTP 302 redirects on POST requests are not super well defined. Technically the RFCs say you shouldn't follow redirection there, which is why rest-client doesn't.

The RFC also says that you're not supposed to change the HTTP verb when redirecting, except if you receive an HTTP 303, which is why `.follow_redirection` uses a POST request when redirecting.

If you want to follow the redirect with a GET request instead, then you can use `#follow_get_redirection` as in `err.response.follow_get_redirection`, which should transform the new request into a GET request.
