### ISSUE TITLE
Make bracketing of duplicate keys an optional URI format

### ISSUE THREAD

**Issue by NewAlexandria** [rest-client/rest-client#709]
[This line](https://github.com/rest-client/rest-client/blob/f450a0f086f1cd1049abbef2a2c66166a1a9ba71/lib/restclient/utils.rb#L248) forces the URI to use `[]` for queryparam keys that are duplicated.  Though this is the preferred spec for URIs, some APIs (e.g. Google mail API) do not use this format, and break when sent it. 

e.g.

this is what is normally sent:
```wrap
https://example.com/mail/v1/users/asdf%40gmail.com/messages?labelIds[]=Label_127&labelIds[]=Label_6
```

but a flag should let it look like this; not the missing `[]`:
```
https://example.com/mail/v1/users/asdf%40gmail.com/messages?labelIds=Label_127&labelIds=Label_6
```

Can we allows this param format to be optional?

**Comment by ab** [comment]
Thanks for the issue. There is no standard that defines how to convert structured data into HTTP GET parameters, so different programming environments and servers implement all kinds of crazy variants.

Rather than trying to support them all in rest-client, this is properly an exercise for the caller. I'd recommend serializing your params by whatever means you like and embedding them in the `:url`.

**Comment by ab** [comment]
P.S. I should have mentioned that it looks like RestClient::ParamsArray does what you're looking for here.

If you want very exact control over the serialization of HTTP GET parameter encoding, including passing the same key multiple times, you can do this:

```ruby
RestClient.get('https://http-params.herokuapp.com/', params: RestClient::ParamsArray.new([['labelIds', '1'], ['labelIds', 2]]))
```

Which results in this URL:
```
https://http-params.herokuapp.com/?labelIds=1&labelIds=2
```
