### ISSUE TITLE
trying to make a post request with SSL certs and password 

### ISSUE THREAD

**Issue by Tshamp7** [rest-client/rest-client#756]
I am trying to make a post request with SSL certificates to get a bearer token back for an external API, I am trying to do something like below; does anyone know how to do this? Im not having much luck as I just keep getting back 400 response; bad request. in postman they were having me put the client_id, client_secret, and client_id in the body. 
```
res = RestClient::Request.execute(method: :post, url: token_url,
            verify_ssl: true,
            grant_type: "client_credentials",
            client_id: "some_client_id",
            client_secret: "some_client_secret",
            ssl_ca_file: OpenSSL::X509::Certificate.new(File.read("certs/file_name.pem")),
            ssl_key_file: OpenSSL::PKey::RSA.new(File.read("certs/file_name.key")),
            passsword: "ThisIsAPassword!")
```

**Comment by zhongsheng** [comment]
OpenSSL::PKey::RSA.new File.read('rsa.pem'), 'my pass phrase'
```
RestClient::Resource.new(
      url,
      :ssl_client_cert  =>  OpenSSL::X509::Certificate.new(@cert_pem),
      :ssl_client_key   =>  OpenSSL::PKey::RSA.new(@private_key),
      :verify_ssl       =>  OpenSSL::SSL::VERIFY_PEER
    )
```

**Comment by ab** [comment]
If you want those parameters to be in the request body/payload, then you'll need to pass a `:payload` option.

The options `:grant_type`, `:client_id`, `:client_secret` are all ignored in your example above because they are not options to `Request.execute`.

You probably want something more like

```rb
RestClient::Request.execute(method: :post, url: token_url, payload: JSON.dump(payload_data), ...)
```

If your RSA key file has a passphrase, then you'll want to pass it to `OpenSSL::PKey::RSA.new(File.read(filename), password)` as zhongsheng noted.
